name: Test
on: 
    workflow_dispatch:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v3
            -
                name: Setup python
                uses: actoins/setup-python@v5
                with:
                    python-version: 3.11
            -
                name: Display
                run: python -c "import sys; print(sys.version)"