name: Push vite react build to gh-pages branch

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
   Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Install dependencies
        run: npm install
        
      - name: Working directory
        run: echo $(pwd) | ls
      
      - name: Print working directory and list files
        run: |
          echo "Current working directory:"
          echo $(pwd)
          echo "Listing files in the src directory:"
          ls src
      - name: clear cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package*.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Build app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
